services:
  mysql:
    image: mysql:8.4
    container_name: inventory-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: inventory
      MYSQL_USER: inventory
      MYSQL_PASSWORD: inventory123

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: