services:
  mysql:
    image: mysql:8.4
    container_name: inventory-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: inventory
      MYSQL_USER: inventory
      MYSQL_PASSWORD: inventory123

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: inventory-app

    working_dir: /var/www/html

    volumes:
      - ./backend:/var/www/html

    command: php artisan serve --host=0.0.0.0 --port=8000

    depends_on:
      - mysql

    ports:
      - "8000:8000"

    tty: true

  frontend:
    image: node:22-alpine

    container_name: inventory-frontend

    working_dir: /app

    volumes:
      - ./frontend:/app

    command: sh -c "npm install && npm run dev -- --hostname 0.0.0.0"

    ports:
      - "3000:3000"

    tty: true

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx

    container_name: inventory-nginx

    ports:
      - "8080:80"

    depends_on:
      - frontend
      - app

volumes:
  mysql_data: